{
  "schema_version": 2,
  "app_version": "dev",
  "name": "test",
  "display": {
    "precision": 3
  },
  "units": {
    "angle": "dd.mmss",
    "distance": "m"
  },
  "points": {},
  "lines": {},
  "history": []
}
